version: '3.8'
services:
  postgres:
    image: postgres:14.2-alpine
    volumes:
            - postgres:/var/lib/postgresql/data
    env_file: .env
    ports:
    - "54321:5432"

volumes:
  postgres:
